version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: FirstExampleDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "7575:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
